### ISSUE TITLE
Code signature is broken

### ISSUE THREAD

**Issue by stisti** [stisti/jenkins-app#1]
codesign -v Jenkins.app
Jenkins.app: code or signature modified

**Comment by stisti** [comment]
It seems AppleScript Editor cannot produce a working code signature. Maybe I can sign it as a separate step of the build?

**Comment by pajp** [comment]
https://github.com/stisti/jenkins-app/pull/16

**Comment by stisti** [comment]
Latest version has a valid signature, albeit by a self-signed certificate.
