### ISSUE TITLE
Download of jenkins.war fails silently

### ISSUE THREAD

**Issue by stisti** [stisti/jenkins-app#11]
From a friend:

Yeah thought so. Picked the one from GitHub, it said it would download Jenkins and then nothing happened...

I do have ~/Library/Caches, though

Yeah, but it's empty

nothing after "2012-04-03 22:33:42,482 Jenkins.app: downloading jenkins.war to /Users/rasmus/Library/Caches/org.jenkins-ci.jenkins/jenkins.war"

**Comment by stisti** [comment]
No idea what is going on... There is an error handler that should tell the user if curl fails to download jenkins.war. Have to test it more.

**Comment by pajp** [comment]
When I tried again with the latest version, everything seems to work fine.

**Comment by stisti** [comment]
Whee! Thanks for testing again! I'll close this.
