### ISSUE TITLE
Automatic start is blocked by popups

### ISSUE THREAD

**Issue by incloud** [stisti/jenkins-app#12]
I installed your Jenkins app and everything works fine so far. I set the Mac OS account to "automatic login" and set your Jenkins app to start after the user logged in (like you describe in your readme).

The problem is that although your Jenkins app is started, Jenkins CI doesn't start running until I confirm the two popups that appear on every start (one asks for JVM parameters and one asks for Jenkins parameters).

Is there a switch that lets me disable these popups?

We are going to use your app on a CI server that is unattended most of the time. It would be great if Jenkins could start running after a reboot without human help.

**Comment by stisti** [comment]
Currently there is no such switch. I'll have to think about how to implement it. Thanks for the feedback!

**Comment by stisti** [comment]
Fixed by build 30 available in the downloads.
