### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by imod** [stisti/jenkins-app#13]
When double clicking the app it downloads whether it should download the WAR.
After pressing OK, it fails with a dialog message:

...
curl error: The command exited with a non-zero status.
curl exit code was 6

**Comment by stisti** [comment]
Curl exit code        6      Couldn't resolve host. The given remote host was not resolved.

Hmm... That seems to be a transient problem. I tried

```
curl -sfL http://mirrors.jenkins-ci.org/war/latest/jenkins.war
```

which is what Jenkins.app does and it works. Could you try again?

**Comment by stisti** [comment]
I haven't heard back from the reporter and am unable to reproduce the issue. Assuming the issue is no longer valid.
