### ISSUE TITLE
Installer help

### ISSUE THREAD

**Issue by iOS-user** [stisti/jenkins-app#15]
Hi Sami. This isn't a bug on your end...but was wondering if you know what are the differences between the jenkins.pkg and your jenkins.app installation.

I cannot run Xcode "instruments -t path/Automation.tracetemplate path/iPhone.app" command with jenkins.pkg installer. It seems to fail when running the full instruments command. Using your installer it works, so it must be the way it is installed with jenkins-1.474.pkg.

I've done everything possible. Changing the user/group to user:staff, as well as /Users/Shared/Jenkins, and launching relaunching with sudo launchctl unload -w org.jenkins-ci.plist; sudo launchctl load -w org.jenkins-ci.plist;

**Comment by stisti** [comment]
I think you have the same issue as described in https://github.com/stisti/jenkins-app in the README section "Why would I want to use Jenkins.app". I do not know what is it Instruments needs, but apparently it needs to be executed in Aqua session.

-- Sami

iOS-userreply@reply.github.com kirjoitti 13.7.2012 kello 2.19:

**Comment by stisti** [comment]
I guess there isn't anything else happening here, so closing the case.
