### ISSUE TITLE
Cannot find any plugins

### ISSUE THREAD

**Issue by President** [stisti/jenkins-app#18]
I have just installed and started Jenkins.app.
But I see it cannot find any of the plugins: http://cl.ly/image/420v1a3i383b 
So it is totally unusable now.
Please fix this.

Thanks.

**Comment by President** [comment]
After couple of minutes plugins appeared. So the problem is only that it doesn't display them immediately after start or at least doesn't tell that it is downloading the list.

**Comment by stisti** [comment]
The update center and plugin management is all provided by Jenkins itself,
so unfortunately there isn't anything I can do about it.

If I remember correctly, the update center and plugin list are actually
fetched by your browser from the nearest Jenkins site mirror. If you can
make your connection browser talk to a better mirror, it might help.
Perhaps you can get help from jenkins users mailing list.

-- Sami

2012/12/3 Konstantin Trunin notifications@github.com
