### ISSUE TITLE
locked out myself

### ISSUE THREAD

**Issue by n811mare** [stisti/jenkins-app#20]
Hi there,
i accidentally locked out myself from my newly installed jenkins
by activating the secured mode of jenkins without having any user created.
normally one would delete or edit /var/lib/jenkins on linux
but how can i disable the secured mod in jenkins app on a mac ??

Thanks for all help ^^

**Comment by stisti** [comment]
/var/lib/jenkins is conventionally the JENKINS_HOME directory set by Jenkins Linux installers.

The default JENKINS_HOME is ~/.jenkins and Jenkins.app does not change that. So go to .jenkins directory under the account you use to run Jenkins.app and edit config.xml to disable security.

**Comment by n811mare** [comment]
Thanks a lot, 
i missed to check for invisible directories^^
