### ISSUE TITLE
change Jenkins port

### ISSUE THREAD

**Issue by tangzhen** [stisti/jenkins-app#23]
I want to change the port of Jenkins server, but I tried the command:

```
sudo defaults write /Library/Preferences/org.jenkins-ci httpPort 7070
```

But it seems doesn't work.

**Comment by stisti** [comment]
Yes that works in the official Jenkins, but you have to change the http port in a different way in Jenkins.app.

The Jenkins app pops up two dialogs when it starts up. In the first dialog you can set the JVM options and in the second dialog you can set the Jenkins options like the http port. See https://wiki.jenkins-ci.org/display/JENKINS/Starting+and+Accessing+Jenkins

-- Sami

**Comment by ghost** [comment]
Is there any way to modify the jenkins params when launching jenkins as login item?

**Comment by stisti** [comment]
When Jenkins.app starts, it displays a dialog asking if you want to
customize Jenkins startup. If you click "Change defaults", you get to
change both the JVM command line options (the options before -jar option)
and Jenkins options (the options after -jar). Jenkins.app will remember the
settings you specify as the new defaults.

If you just wait for 15 seconds, Jenkins.app will automatically start up
using the defaults.

2014-12-12 14:37 GMT+02:00 ronjawilkening notifications@github.com:
