### ISSUE TITLE
Static-analysis.jelly

### ISSUE THREAD

**Issue by reyandersen** [stisti/jenkins-app#24]
Hi there.
I really like how easy it is to get going with this app compared to a "normal" Jenkins install.

I have been trying to find out if I can use the static-analysis.jelly can be used with this app. But I have not been able to find anything written about it.

So thought I would give it a try asking here.

Cheers
Lasse

**Comment by stisti** [comment]
I don't see why it would not work with Jenkins.app. Jenkins.app is just a
wrapper for Jenkins. I think you should just go ahead and try it the same
way you would with any other Jenkins.

2014-11-11 14:37 GMT+02:00 reyandersen notifications@github.com:
