### ISSUE TITLE
use jenkins-app on a exisiting jenkins instance 

### ISSUE THREAD

**Issue by shams-ahmed** [stisti/jenkins-app#28]
my mac ready has jenkins running with a few jobs... is it possible to use this app to the manage that instance instead of creating another one?

**Comment by stisti** [comment]
You could do it by doing something like this:

```
mkdir ~/.jenkins
sudo rsync -a /Users/Shared/Jenkins/Home/ ~/.jenkins/
sudo chown -R $USER ~/.jenkins
```

Then stop the old Jenkins and start Jenkins.app

**Comment by shams-ahmed** [comment]
thanks!
