### ISSUE TITLE
Upgrade notification

### ISSUE THREAD

**Issue by stisti** [stisti/jenkins-app#4]
Jenkins.app should be able to notify user when a new version of Jenkins.app is available.

**Comment by afeick** [comment]
not sure if it would help your project, but here's the series of terminal commands I use to update jenkins locally

launchctl unload /Users/jenkins/Library/LaunchAgents/org.jenkins-ci.plist
sudo mv /Applications/Jenkins/jenkins.war /Applications/Jenkins/jenkins-prev.war 
rm -f /tmp/jenkins.war
curl -L http://mirrors.jenkins-ci.org/war/latest/jenkins.war > /tmp/jenkins.war
sudo mv /tmp/jenkins.war /Applications/Jenkins
sudo chown root:admin /Applications/Jenkins/jenkins.war 
sudo chmod 755 /Applications/Jenkins/jenkins.war 
sudo xattr -c /Applications/Jenkins/jenkins.war
launchctl load /Users/jenkins/Library/LaunchAgents/org.jenkins-ci.plist

**Comment by stisti** [comment]
Thanks, but this issue is about updating Jenkins.app, which is the app-wrapper on top of Jenkins. Jenkins itself is able to take care of updating the actual jenkins.war.

**Comment by stisti** [comment]
Fixed in build 17
